BEGIN
  DBMS_OUTPUT.PUT_LINE(BINARY_FLOAT_NAN);
  DBMS_OUTPUT.PUT_LINE(BINARY_FLOAT_INFINITY);
  DBMS_OUTPUT.PUT_LINE(BINARY_FLOAT_MAX_NORMAL);
  DBMS_OUTPUT.PUT_LINE(BINARY_FLOAT_MIN_NORMAL);
  DBMS_OUTPUT.PUT_LINE(BINARY_FLOAT_MAX_SUBNORMAL);
  DBMS_OUTPUT.PUT_LINE(BINARY_FLOAT_MIN_SUBNORMAL);
END;
